/** Functional groups shared by Home and navigation; independent of layout templates. */
export const TOOL_GROUPS = [
  {
    name: "Data formats",
    glyph: "{}",
    examples: "JSON, YAML, CSV, SQL",
    ids: [
      "json-format",
      "xml-format",
      "sql-format",
      "yaml-format",
      "graphql-format",
      "json-to-yaml",
      "yaml-to-json",
      "json-to-csv",
      "csv-to-json",
      "json-to-php",
      "php-to-json",
      "php-serialize",
      "php-unserialize",
      "json-stringify",
      "json-to-code",
      "word-to-markdown",
      "markdown-format",
    ],
  },
  {
    name: "Encoding",
    glyph: "↔",
    examples: "Base64, binary, Unicode",
    ids: [
      "base64",
      "backslash-escape",
      "quote-helper",
      "utf8",
      "binary-code",
      "morse-code",
      "hex-to-ascii",
      "ascii-to-hex",
      "number-base-converter",
      "unicode-text-converter",
      "unicode-to-text-converter",
      "nato-phonetic-converter",
      "pig-latin-converter",
      "phonetic-spelling-converter",
    ],
  },
  {
    name: "Time & dates",
    glyph: "◷",
    examples: "Unix time, cron, dates",
    ids: [
      "unix-time",
      "cron-parser",
      "roman-date-converter",
      "random-date",
      "random-month",
    ],
  },
  {
    name: "Web & URLs",
    glyph: "</>",
    examples: "HTML, CSS, URLs, JavaScript",
    ids: [
      "html-beautify",
      "css-beautify",
      "scss-beautify",
      "less-beautify",
      "javascript-beautify",
      "typescript-beautify",
      "erb-format",
      "html-to-jsx",
      "html-to-markdown",
      "svg-to-css",
      "curl-to-code",
      "query-string-to-json",
      "url",
      "url-parser",
      "utm-generator",
      "slugify-url",
      "html-entity",
      "html-preview",
      "markdown-preview",
      "color-converter",
    ],
  },
  {
    name: "Security",
    glyph: "◇",
    examples: "JWT, hashes, certificates",
    ids: [
      "jwt-debugger",
      "cert-decoder",
      "hash-generator",
      "password-generator",
      "aes-encrypt",
      "rot13",
      "caesar-cipher",
    ],
  },
  {
    name: "Text",
    glyph: "Aa",
    examples: "Compare, clean, count, search",
    ids: [
      "delimiter-converter",
      "case-converter",
      "line-sort-dedupe",
      "sort-words",
      "number-sorter",
      "duplicate-word-finder",
      "text-replace",
      "character-remover",
      "whitespace-remover",
      "line-break-remover",
      "text-formatting-remover",
      "remove-underscores",
      "em-dash-remover",
      "plain-text-converter",
      "reverse-text-generator",
      "sentence-counter",
      "word-frequency-counter",
      "regex-tester",
      "text-diff",
      "string-inspector",
    ],
  },
  {
    name: "Fonts",
    glyph: "𝑨",
    examples: "Unicode styles, social fonts",
    ids: [
      "bold-text-generator",
      "italic-text-converter",
      "underline-text-generator",
      "strikethrough-text-generator",
      "small-text-generator",
      "subscript-generator",
      "superscript-generator",
      "wide-text-generator",
      "double-struck-text-generator",
      "bubble-text-generator",
      "gothic-text-generator",
      "cursed-text-generator",
      "slash-text-generator",
      "stacked-text-generator",
      "big-text-converter",
      "typewriter-text-generator",
      "fancy-text-generator",
      "cute-font-generator",
      "aesthetic-text-generator",
      "facebook-font-generator",
      "instagram-font-generator",
      "x-font-generator",
      "tiktok-font-generator",
      "discord-font-generator",
      "whatsapp-font-generator",
      "wingdings-converter",
      "upside-down-text-generator",
      "mirror-text-generator",
    ],
  },
  {
    name: "Images",
    glyph: "▧",
    examples: "Convert images, OCR, QR codes",
    ids: [
      "jpg-to-png-converter",
      "png-to-jpg-converter",
      "jpg-to-webp-converter",
      "webp-to-jpg-converter",
      "png-to-webp-converter",
      "webp-to-png-converter",
      "svg-to-png-converter",
      "image-to-text-converter",
      "base64-image",
      "qr-code",
      "ascii-art-generator",
      "word-cloud-generator",
    ],
  },
  {
    name: "Generators",
    glyph: "✧",
    examples: "UUIDs, sample text, random data",
    ids: [
      "uuid-ulid",
      "random-string",
      "lorem-ipsum",
      "random-number",
      "random-letter",
      "random-ip",
      "random-choice",
      "repeat-text-generator",
      "invisible-text-generator",
      "apa-format-generator",
      "markdown-table-generator",
    ],
  },
];
const groupByTool = new Map(
  TOOL_GROUPS.flatMap((group) =>
    group.ids.map((id) => [id, group.name] as const),
  ),
);
export const ALL_CATEGORIES = TOOL_GROUPS.map((group) => group.name);
export function getToolCategory(toolId: string): string {
  return groupByTool.get(toolId) ?? "Other";
}
export function getToolGlyph(toolId: string): string {
  return (
    TOOL_GROUPS.find((group) => group.name === getToolCategory(toolId))
      ?.glyph ?? "◇"
  );
}
